---
- name: Add a user to a password file and ensure permissions are set
  community.general.htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ item.name }}"
    password: "{{  item.passwd }}"
    owner: root
    group: nginx
    mode: 0640
    crypt_scheme: md5_crypt
  no_log: true
  loop: "{{ users }}"
