---
- name: Installing a python3-pip
  yum:
    name: python3-pip
    state: present
  notify: restart nginx

- name: "Installing a cryptography module"
  ansible.builtin.pip:
    name: cryptography
      
- name: "Generating a private key for the {{ server_name }}"
  community.crypto.openssl_privatekey:
    path: "{{ ssl_key }}"
    mode: "0640"
    type: RSA
    size: 2048
    state: present
  
- name: "Generating a Certificate Signing Request(CSR) for self signed certificate"
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ ssl_key }}"
    common_name: "{{ cert_common_name }}"
    organization_name: "{{ cert_org_name }}"
  register: csr

- name: "Generating a self-signed certificate for {{ cert_common_name }}"
  community.crypto.x509_certificate:
    path: "{{ ssl_crt }}"
    privatekey_path: "{{ ssl_key }}"
    csr_content: "{{ csr.csr }}"
    provider: selfsigned
    selfsigned_not_after: "+365d" 
    mode: "0644"
    state: present
    mode: "0755"
